name: Build Linux Wheels

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

env:
  PIP_BREAK_SYSTEM_PACKAGES: 1

jobs:
  build-linux-wheels:
    name: linux-wheel-${{ matrix.target.arch }}-${{ matrix.python }}
    runs-on: ${{ matrix.target.runner }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        python: ["cp39", "cp310", "cp311", "cp312", "cp313"]
        target:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          python -m pip install packaging
          python update-nightly-build-version.py
        working-directory: scripts

      - name: Create source distribution
        working-directory: ./scripts/pip-package/
        run: |
          rm -rf wheelhouse koredb.tar.gz
          mkdir wheelhouse
          python package_tar.py koredb.tar.gz

      - name: Build wheels
        working-directory: ./scripts/pip-package/
        env:
          CIBW_BUILD: ${{ matrix.python }}-*
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS_LINUX: ${{ matrix.target.arch }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
          CIBW_BUILD_VERBOSITY: 3
        run: pipx run --spec 'cibuildwheel>=3.0' cibuildwheel --output-dir wheelhouse koredb.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: linux-wheels-${{ matrix.target.arch }}-${{ matrix.python }}
          path: ./scripts/pip-package/wheelhouse/*.whl
          if-no-files-found: error
