name: Build WebAssembly module

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build-wasm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: tools/wasm
        run: npm i
      
      - name: Build WebAssembly package
        working-directory: tools/wasm
        run: |
          source /home/runner/emsdk/emsdk_env.sh
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: koredb-deploy-wasm
          path: tools/wasm/koredb-wasm.tar.gz
          retention-days: 1
