name: Build Windows Precompiled Binaries

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      isNightly:
        type: boolean
        required: true
        default: false

jobs:
  build-precompiled-bin:
    runs-on: self-hosted-windows
    steps:
      - uses: actions/checkout@v4

      - name: Update nightly version
        if: ${{ inputs.isNightly == true }}
        run: |
          pip3 install packaging
          python3 update-nightly-build-version.py
        working-directory: ./scripts

      - name: Build precompiled binaries
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          make NUM_THREADS=%NUMBER_OF_PROCESSORS%
          make install

      - name: Collect artifacts
        shell: cmd
        run: |
          move install\include\koredb.h
          move install\include\koredb.hpp
          move install\bin\koredb_shared.dll
          move install\lib\koredb_shared.lib
          move install\bin\koredb_shell.exe koredb.exe

      - uses: actions/upload-artifact@v4
        with:
          name: libkoredb-windows-x86_64
          path: |
            koredb.h
            koredb.hpp
            koredb_shared.dll
            koredb_shared.lib

      - uses: actions/upload-artifact@v4
        with:
          name: koredb_cli-windows-x86_64
          path: koredb.exe
